### ISSUE TITLE
Mark Mikroelektronika Mini-32 board as supported

### ISSUE THREAD

**Issue by martonmiklos** [thotypous/mikroe-uhb#6]
Hello,

I have Mikroelektronika Mini-32 board (http://www.mikroe.com/mini/pic32), and I have been able to use it with the mikroe-uhb tool without any problems under Ubuntu 14.04.5.
I think it would be useful to add it to the README.md as a supported device.
If you need any further logs as evidence please let me know!

Thank you for creating this project!

**Comment by thotypous** [comment]
Thanks for testing! I've added it to the README.
